### ISSUE TITLE
Account for current wheel steering angle in the odometry calculations in state_estimator

### ISSUE THREAD

**Issue by markmellors** [thingswebuilt/osod24_firmware#20]
The calculations of `distance_travelled`, and `estimatedState.velocity`, which are both based on wheel rotation, should account for the angle of the steerable wheels and use the forward component of their movement, rather than their total movement. 
For this calculation to be possible, `state_estimator` needs to know the currently requested steering angle. Ideally, `state_estimator` should estimate the true steering angle by applying a (rate limiting) low pass filter to the requested steering angle.

**Comment by robberwick** [comment]
This probably has a dependency on #14

**Comment by markmellors** [comment]
yeah, I hadn't spotted you'd already raised that
