### ISSUE TITLE
statemanager house keeping - DRYness of servo handling

### ISSUE THREAD

**Issue by markmellors** [thingswebuilt/osod24_firmware#22]
There's a lot of repetition around how the steering servos are handled in `statemanager` , in particular, how they're initialised and how they're disabled when a wheel isn't moving

**Comment by robberwick** [comment]
I think in particular we're talking about https://github.com/thingswebuilt/osod24_firmware/blob/main/libs%2Fstatemanager%2Fsrc%2Fstatemanager.cpp#L46 - is that correct?

**Comment by markmellors** [comment]
yes, and I was thinking that https://github.com/thingswebuilt/osod24_firmware/blob/8d732d777120b27ca8d1045995420f2cbed474a7/libs/statemanager/src/statemanager.cpp#L19 onwards is repetitive

**Comment by markmellors** [comment]
addressed by PR#24
